spring.application.name=chat-lab

# We read the API key from environment variables for security.
# If not set, it defaults to 'insert_your_key_here'
llm.api.key=${API_KEY:insert_your_key_here}
llm.api.url=https://openrouter.ai/api/v1/chat/completions